### ISSUE TITLE
Improve Security Measures

### ISSUE THREAD

**Issue by pcchin** [Paxtan-Development/study-assistant#51]
Better implementation and storage of salts may be needed, may lose backwards compatibility when exporting .subject files.

**Tasks to be completed:**

- [x] Rework SecurityFunctions entirely (Simplify/rework certain encryption, decryption & hashing functions, don't' use ECB and CBC)

- [x] Implement .subject2 file format (Different encryption method, more secure than .subject, lose backwards compatibility)

- [x] Implement database object for notes in subjects, will lose backwards compatibilit

- [x] Encrypt database for notes

- [x] Encrypt database for projects

- [x] Implement EncryptedSharedPreferences to store certain constants

**Comment by pc-chin** [comment]
**Tasks to be completed:**

- [ ] Fix SecurityFunctions Implementation (Better implementation and storage of salts may be needed, maintain old methods for backwards compatability)

- [ ] Implement .subject2 file format (Different encryption method, more secure than .subject)

- [ ] Encrypt database for notes (May lose backwards compability)

- [ ] Encrypt database for projects

- [ ] Use C++ file to obfuscate certain String constants

**Comment by pcchin** [comment]
Client-server communications not needed for now as bug reports and user feedback are now handled by Sentry

**Comment by pcchin** [comment]
Implement EncryptedSharedPreferences is only available for devices with Android Marshmallow (23) and above.
